import type { CapabilityDef, CapabilityType } from './types'

export const CAPABILITIES: Record<CapabilityType, CapabilityDef> = {
  llm: {
    type: 'llm',
    label: 'LLM',
    icon: 'lucide:brain-circuit',
    description: 'Reason and generate language',
    accent: '#2dd4bf',
    inputs: [{ id: 'context', label: 'Context', type: 'text' }],
    outputs: [{ id: 'response', label: 'Response', type: 'text' }],
  },
  local: {
    type: 'local',
    label: 'Local Model',
    icon: 'lucide:hard-drive-download',
    description: 'Run a model in your browser — no API key',
    accent: '#38bdf8',
    inputs: [{ id: 'context', label: 'Context', type: 'text' }],
    outputs: [{ id: 'response', label: 'Response', type: 'text' }],
  },
  memory: {
    type: 'memory',
    label: 'Memory',
    icon: 'lucide:database',
    description: 'Persist conversation context',
    accent: '#a78bfa',
    inputs: [{ id: 'value', label: 'Value', type: 'any' }],
    outputs: [{ id: 'stored', label: 'Stored', type: 'any' }],
  },
  planner: {
    type: 'planner',
    label: 'Planner',
    icon: 'lucide:list-todo',
    description: 'Break goals into steps',
    accent: '#fbbf24',
    inputs: [{ id: 'goal', label: 'Goal', type: 'text' }],
    outputs: [{ id: 'plan', label: 'Plan', type: 'list' }],
  },
  browser: {
    type: 'browser',
    label: 'Browser',
    icon: 'lucide:globe',
    description: 'Fetch the text of a live web page',
    accent: '#60a5fa',
    inputs: [{ id: 'url', label: 'URL', type: 'text' }],
    outputs: [
      { id: 'pages', label: 'Pages', type: 'list' },
      { id: 'content', label: 'Content', type: 'text' },
    ],
  },
  github: {
    type: 'github',
    label: 'GitHub',
    icon: 'lucide:github',
    description: 'Read repositories and issues',
    accent: '#94a3b8',
    inputs: [],
    outputs: [{ id: 'repos', label: 'Repos', type: 'list' }],
  },
  filesystem: {
    type: 'filesystem',
    label: 'Filesystem',
    icon: 'lucide:folder',
    description: 'Read and write local files',
    accent: '#f472b6',
    inputs: [{ id: 'path', label: 'Path', type: 'text' }],
    outputs: [{ id: 'content', label: 'Content', type: 'text' }],
  },
  python: {
    type: 'python',
    label: 'Python',
    icon: 'lucide:terminal',
    description: 'Run Python scripts',
    accent: '#4ade80',
    inputs: [{ id: 'code', label: 'Code', type: 'text' }],
    outputs: [{ id: 'result', label: 'Result', type: 'text' }],
  },
  rag: {
    type: 'rag',
    label: 'RAG',
    icon: 'lucide:search',
    description: 'Retrieve from knowledge base',
    accent: '#38bdf8',
    inputs: [{ id: 'query', label: 'Query', type: 'text' }],
    outputs: [{ id: 'documents', label: 'Documents', type: 'list' }],
  },
  finetune: {
    type: 'finetune',
    label: 'Fine-tune',
    icon: 'lucide:graduation-cap',
    description: 'Train a model on a dataset',
    accent: '#fb7185',
    inputs: [
      { id: 'dataset', label: 'Dataset', type: 'text' },
      { id: 'baseModel', label: 'Base model', type: 'text' },
    ],
    outputs: [{ id: 'model', label: 'Trained model', type: 'text' }],
  },
  news: {
    type: 'news',
    label: 'News',
    icon: 'lucide:newspaper',
    description: 'Fetch live news articles',
    accent: '#fbbf24',
    inputs: [{ id: 'query', label: 'Query', type: 'text' }],
    outputs: [
      { id: 'articles', label: 'Articles', type: 'list' },
      { id: 'headline', label: 'Headline', type: 'text' },
    ],
  },
  imagegen: {
    type: 'imagegen',
    label: 'ImageGen',
    icon: 'lucide:image-plus',
    description: 'Generate an image from a prompt',
    accent: '#fb7185',
    inputs: [{ id: 'prompt', label: 'Prompt', type: 'text' }],
    outputs: [{ id: 'imageUrl', label: 'Image URL', type: 'text' }],
  },
  mcp: {
    type: 'mcp',
    label: 'MCP Tool',
    icon: 'lucide:plug-zap',
    description: 'Call a real tool on a configured MCP server (Stripe, Supabase, GitHub…)',
    accent: '#22d3ee',
    inputs: [{ id: 'input', label: 'Input', type: 'text' }],
    outputs: [{ id: 'result', label: 'Result', type: 'any' }],
  },
  tool: {
    type: 'tool',
    label: 'Tool',
    icon: 'lucide:wrench',
    description: 'MCP tool node (branded by its server)',
    accent: '#22d3ee',
    inputs: [{ id: 'input', label: 'Input', type: 'text' }],
    outputs: [{ id: 'result', label: 'Result', type: 'any' }],
  },
  worker: {
    type: 'worker',
    label: 'Worker',
    icon: 'lucide:bot',
    description: 'Delegate a subtask to a reusable sub-brain (agent or pipeline)',
    accent: '#a78bfa',
    inputs: [{ id: 'input', label: 'Input', type: 'any' }],
    outputs: [{ id: 'result', label: 'Result', type: 'any' }],
  },
  output: {
    type: 'output',
    label: 'Output',
    icon: 'lucide:square-arrow-out-up-right',
    description: 'Deliver the final result; downloads a Markdown report',
    accent: '#34d399',
    inputs: [
      { id: 'result', label: 'Result', type: 'any' },
      { id: 'download', label: 'Download report', type: 'boolean' },
    ],
    outputs: [],
  },
}

export const CAPABILITY_LIST: CapabilityDef[] = Object.values(CAPABILITIES)